#!/bin/bash

# Stackr Environment Setup Script
#
# PURPOSE: Creates a basic .env file for local development
# RELATED: ENVIRONMENT_VARIABLES.md, Docker setup
# TAGS: setup, environment, development

set -e

echo "🎯 Setting up Stackr environment variables..."
echo "=============================================="

# Check if .env already exists
if [ -f ".env" ]; then
    echo "⚠️  .env file already exists!"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Setup cancelled. Existing .env file preserved."
        exit 1
    fi
fi

# Create .env file with basic development configuration
cat > .env << 'EOF'
# Stackr Bitcoin DCA Application - Development Environment
# Generated by setup-env.sh

# Application Configuration
NODE_ENV=development
PORT=3000
DEBUG=stackr:*
LOG_LEVEL=debug

# Bitcoin Knots RPC Configuration
BITCOIN_RPC_HOST=localhost
BITCOIN_RPC_PORT=18332
BITCOIN_RPC_USER=stackr
BITCOIN_RPC_PASSWORD=stackr_password
BITCOIN_NETWORK=testnet
BITCOIN_RPC_TIMEOUT=30000
BITCOIN_RPC_RETRY_ATTEMPTS=3

# Database Configuration
DATABASE_PATH=./data/stackr.db
DATABASE_MIGRATIONS_PATH=./src/database/migrations

# Development Settings
WATCH=true
HOT_RELOAD=true

# Security Configuration (Change these in production!)
JWT_SECRET=dev-jwt-secret-change-in-production
SESSION_SECRET=dev-session-secret-change-in-production
API_RATE_LIMIT=100
API_RATE_LIMIT_WINDOW=900000

# Feature Flags
FEATURE_DCA_AUTOMATION=true
FEATURE_SELF_CUSTODY_WITHDRAWALS=true
FEATURE_LANGGRAPH_ORCHESTRATION=true
FEATURE_PUSH_NOTIFICATIONS=false
FEATURE_EMAIL_NOTIFICATIONS=false

# Development Overrides (for Docker)
BITCOIN_RPC_HOST_OVERRIDE=bitcoind
BITCOIN_RPC_PORT_OVERRIDE=18332

# Future Configuration (commented out)
# EXCHANGE_API_KEY=your-exchange-api-key
# EXCHANGE_API_SECRET=your-exchange-api-secret
# EXCHANGE_NAME=coinbase-pro
# PUSH_NOTIFICATION_ENABLED=false
# EMAIL_ENABLED=false
# MONITORING_ENABLED=false
EOF

echo "✅ .env file created successfully!"
echo ""
echo "📋 Environment variables configured:"
echo "   • Application: NODE_ENV, PORT, DEBUG"
echo "   • Bitcoin Knots: RPC connection settings"
echo "   • Database: SQLite configuration"
echo "   • Security: Basic JWT and session secrets"
echo "   • Features: Core features enabled"
echo ""
echo "🔧 Next steps:"
echo "   1. Review and customize .env file if needed"
echo "   2. Run: npm install"
echo "   3. Run: ./scripts/dev/start-testnet.sh"
echo ""
echo "📖 For complete environment variable reference, see: ENVIRONMENT_VARIABLES.md" 