name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  NODE_ENV: test
  PORT: 3000
  BITCOIN_RPC_HOST: localhost
  BITCOIN_RPC_PORT: 18332
  BITCOIN_RPC_USER: testuser
  BITCOIN_RPC_PASS: testpass

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  docker-test:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t stackr:test .

      - name: Test Docker container startup
        run: |
          docker run --rm -d --name stackr-test -p 3000:3000 stackr:test
          sleep 10
          curl -f http://localhost:3000/health || exit 1
          docker stop stackr-test

  integration-test:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'

    services:
      # Mock Bitcoin RPC service for integration tests
      bitcoin-rpc:
        image: kylemanna/bitcoind:latest
        options: >-
          --health-cmd "bitcoin-cli -regtest getblockchaininfo"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 18332:18332
        env:
          BITCOIN_RPC_USER: testuser
          BITCOIN_RPC_PASS: testpass
          BITCOIN_RPC_ALLOW_IP: 0.0.0.0/0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Wait for Bitcoin RPC
        run: |
          timeout 60 bash -c 'until curl -s -u testuser:testpass http://localhost:18332; do sleep 2; done'

      - name: Run integration tests
        run: |
          # TODO: Add integration test script when we have real Bitcoin integration
          echo "Integration tests will be added when Bitcoin RPC integration is implemented"
          npm run build

  docker-compose-test:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start Docker Compose services
        run: |
          docker compose -f docker-compose.yml up -d --build
          sleep 30

      - name: Test application health
        run: |
          curl -f http://localhost:3000/health || exit 1

      - name: Test API endpoints
        run: |
          curl -f http://localhost:3000/ || exit 1
          curl -f http://localhost:3000/api || exit 1

      - name: Cleanup
        if: always()
        run: docker compose down
